[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
